Fix a linking error caused by missing submodule in CI workflow.
Error: improved_sound_mixer.c:5: undefined reference to `SoundMainRAM'
`SoundMainRAM' is in git submodule 'source/gba-hq-mixer'. Remember to clone git submodules before building!